seed: 42
experiment_name: "baseline_ga_svm"
data:
  train_csv: "data/raw/train.csv"
  validation_csv: "data/raw/validation.csv"
  test_csv: "data/raw/test.csv"
  target: "label"             # <- zmień jeśli trzeba
  stratify: true
  header: null                # true|false|null(auto)
  target_candidates: ["target","y","class"]

svm:
  kernel: "rbf"        # rbf|linear|poly|sigmoid
  C: 1.0
  gamma: "scale"
  class_weight: "balanced"

encoding:
  k_per_class: 50   # dostosuj do danych

fitness:
  metric: balanced_accuracy
  class_imbalance_penalty: 0.2

ga:
  population_size: 40
  generations: 20
  tournament_k: 3
  crossover_rate: 0.8
  mutation_rate: 0.05
  elitism: 2
  early_stopping:
    patience: 5
    min_delta: 0.001

val_ga:
  subset_fraction: 0.5        # np. GA szuka najgorszej połowy walidacji
  population_size: 40
  generations: 20
  tournament_k: 3
  crossover_rate: 0.8
  mutation_rate: 0.05
  elitism: 2
  early_stopping:
    patience: 5
    min_delta: 0.001

k_schedule:
  num_cycles: 3       # ile razy przechodzimy TRAIN -> VAL -> TRAIN -> ...
  k_start: 20         # początkowe k na klasę
  k_multiplier: 1.5   # przy przejściu VAL -> TRAIN: k := round(k * 1.5)

